### ISSUE TITLE
Error creating orchestration stacks

### ISSUE THREAD

**Issue by ashanvb** [juliosueiras/provider-jet-openstack#1]
### What happened?
I tried creating a small server in openstack using stackv1 resource and it failed with the following error. 
```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2022-06-21T06:26:51Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-06-21T06:26:51Z
    Message:               create failed: cannot apply: apply failed: Error creating openstack_orchestration_stack_v1: Data in neither json nor yaml format.: : File name: main.tf.json
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                        Age               From                                                                      Message
  ----     ------                        ----              ----                                                                      -------
  Warning  CannotCreateExternalResource  2s (x2 over 11s)  managed/orchestration.openstack.jet.crossplane.io/v1alpha1, kind=stackv1  cannot apply: apply failed: Error creating openstack_orchestration_stack_v1: Data in neither json nor yaml format.: : File name: main.tf.json

```
However I managed to create a security group, key-pairs successfully in openstack. This confirms that openstack provider is working and it can create resources in openstack successfully.

### How can we reproduce it?

I used the following yaml file to create the resource. 

```
apiVersion: orchestration.openstack.jet.crossplane.io/v1alpha1
kind: StackV1
metadata:
  name: crossplane-stack-ashan
spec:
  deletionPolicy: Delete
  forProvider:
    templateOpts:
      Bin: |
        heat_template_version: 2015-04-30
        description: Simple template to deploy a single compute instance
        resources:
          my_instance:
            type: OS::Nova::Server
            properties:
              key_name: my_key
              image: ubuntu-trusty-x86_64
              flavor: m1.small
  providerConfigRef:
    name: provider-config-openstack

```

### What environment did it happen in?
Crossplane version: `v1.8.1`
Provider version: `1.47.0`
